BUGFIX/MEDIUM(redis): Fix redis local facts
 ##### SUMMARY

Since redis-py 2.10.0, `timeout` parameter is replaced by `socket_connect_timeout`

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION
```
__init__() got an unexpected keyword argument 'timeout'
<type 'exceptions.TypeError'>
```